export * from './types';
export * as identity from './identity.service';
export * as admissions from './admissions.service';
export * as enrolment from './enrolment.service';
export * as curriculum from './curriculum.service';
export * as assessment from './assessment.service';
export * as progression from './progression.service';
export * as studentSupport from './student-support.service';
export * as compliance from './compliance.service';
export * as platform from './platform.service';
