import { Router } from 'express';
import { authenticateJWT } from '../middleware/auth';

import { studentsRouter } from './students/students.router';
import { personsRouter } from './persons/persons.router';
import { demographicsRouter } from './demographics/demographics.router';
import { identifiersRouter } from './identifiers/identifiers.router';
import { facultiesRouter } from './faculties/faculties.router';
import { schoolsRouter } from './schools/schools.router';
import { departmentsRouter } from './departments/departments.router';
import { programmesRouter } from './programmes/programmes.router';
import { modulesRouter } from './modules/modules.router';
import { programmeModulesRouter } from './programme-modules/programme-modules.router';
import { programmeApprovalsRouter } from './programme-approvals/programme-approvals.router';
import { applicationsRouter } from './applications/applications.router';
import { qualificationsRouter } from './qualifications/qualifications.router';
import { referencesRouter } from './references/references.router';
import { offersRouter } from './offers/offers.router';
import { interviewsRouter } from './interviews/interviews.router';
import { clearanceChecksRouter } from './clearance-checks/clearance-checks.router';
import { admissionsEventsRouter } from './admissions-events/admissions-events.router';
import { enrolmentsRouter } from './enrolments/enrolments.router';
import { moduleRegistrationsRouter } from './module-registrations/module-registrations.router';
import { programmeRoutesRouter } from './programme-routes/programme-routes.router';
import { assessmentsRouter } from './assessments/assessments.router';
import { marksRouter } from './marks/marks.router';
import { submissionsRouter } from './submissions/submissions.router';
import { moduleResultsRouter } from './module-results/module-results.router';
import { examBoardsRouter } from './exam-boards/exam-boards.router';
import { progressionsRouter } from './progressions/progressions.router';
import { awardsRouter } from './awards/awards.router';
import { transcriptsRouter } from './transcripts/transcripts.router';
import { financeRouter } from './finance/finance.router';
import { attendanceRouter } from './attendance/attendance.router';
import { supportRouter } from './support/support.router';
import { ukviRouter } from './ukvi/ukvi.router';
import { ecClaimsRouter } from './ec-claims/ec-claims.router';
import { appealsRouter } from './appeals/appeals.router';
import { documentsRouter } from './documents/documents.router';
import { communicationsRouter } from './communications/communications.router';
import { dashboardRouter } from './dashboard/dashboard.router';
import { timetableRouter } from './timetable/timetable.router';
import { notificationsRouter } from './notifications/notifications.router';
import { auditLogsRouter } from './audit-logs/audit-logs.router';
import { calendarRouter } from './calendar/calendar.router';
import { statutoryReturnsRouter } from './statutory-returns/statutory-returns.router';
import { reportsRouter } from './reports/reports.router';

export const apiV1Router = Router();
apiV1Router.use(authenticateJWT);

apiV1Router.use('/students', studentsRouter);
apiV1Router.use('/persons', personsRouter);
apiV1Router.use('/demographics', demographicsRouter);
apiV1Router.use('/identifiers', identifiersRouter);
apiV1Router.use('/faculties', facultiesRouter);
apiV1Router.use('/schools', schoolsRouter);
apiV1Router.use('/departments', departmentsRouter);
apiV1Router.use('/programmes', programmesRouter);
apiV1Router.use('/modules', modulesRouter);
apiV1Router.use('/programme-modules', programmeModulesRouter);
apiV1Router.use('/programme-approvals', programmeApprovalsRouter);
apiV1Router.use('/applications', applicationsRouter);
apiV1Router.use('/qualifications', qualificationsRouter);
apiV1Router.use('/references', referencesRouter);
apiV1Router.use('/offers', offersRouter);
apiV1Router.use('/interviews', interviewsRouter);
apiV1Router.use('/clearance-checks', clearanceChecksRouter);
apiV1Router.use('/admissions-events', admissionsEventsRouter);
apiV1Router.use('/enrolments', enrolmentsRouter);
apiV1Router.use('/module-registrations', moduleRegistrationsRouter);
apiV1Router.use('/programme-routes', programmeRoutesRouter);
apiV1Router.use('/assessments', assessmentsRouter);
apiV1Router.use('/marks', marksRouter);
apiV1Router.use('/submissions', submissionsRouter);
apiV1Router.use('/module-results', moduleResultsRouter);
apiV1Router.use('/exam-boards', examBoardsRouter);
apiV1Router.use('/progressions', progressionsRouter);
apiV1Router.use('/awards', awardsRouter);
apiV1Router.use('/transcripts', transcriptsRouter);
apiV1Router.use('/finance', financeRouter);
apiV1Router.use('/attendance', attendanceRouter);
apiV1Router.use('/support', supportRouter);
apiV1Router.use('/ukvi', ukviRouter);
apiV1Router.use('/ec-claims', ecClaimsRouter);
apiV1Router.use('/appeals', appealsRouter);
apiV1Router.use('/documents', documentsRouter);
apiV1Router.use('/communications', communicationsRouter);
apiV1Router.use('/dashboard', dashboardRouter);
apiV1Router.use('/timetable', timetableRouter);
apiV1Router.use('/notifications', notificationsRouter);
apiV1Router.use('/audit-logs', auditLogsRouter);
apiV1Router.use('/calendar', calendarRouter);
apiV1Router.use('/statutory-returns', statutoryReturnsRouter);
apiV1Router.use('/reports', reportsRouter);
